import express  from 'express';
import {login,register,userPostShare,getPosts,getOtpPh, updateProfile, userProfileData, userData, likePost, getUsername, getUserPosts, deletePost, getPosterData, followUser, getSuggestions, getFollowers, getFollowings, unFollowUser, followUsers, getNotification, getAllUsers, removeSuggetion, verifyUser, reportPost} from '../Controllers/authController.js'
const routes=express.Router()
import multer, { memoryStorage } from 'multer'
const storage = memoryStorage()
const upload = multer({ storage: storage })

routes.post("/")
routes.post("/login",login)
routes.get('/verifyuser/:id',verifyUser) 
routes.post("/register",register) 
routes.post("/otp_login",getOtpPh)
routes.post("/userPostShare",upload.single("file"), userPostShare)
routes.get("/getPosts",getPosts)
routes.get("/getUserPosts/:id",getUserPosts) 
routes.get("/getprofile/:id",userProfileData)  
routes.get("/getusers/:id",userData)
routes.get("/getUsername/:id",getUsername) 
routes.get("/getPosterData/:id",getPosterData)
routes.post("/updateprofile",upload.single("profilepicture"),updateProfile)
routes.post("/likepost",likePost)
routes.delete('/deletePost/:id',deletePost) 
routes.get('/getFollowers/:id',getFollowers)
routes.get('/getFollowings/:id',getFollowings)
routes.get("/suggestions/:id",getSuggestions)
routes.put("/:id/follow",followUser)
routes.post("/followUsers/:id",followUsers)
routes.post("/unFollowUser/:id",unFollowUser)
routes.get('/getnotification/:id',getNotification)
routes.get('/getallusers/:id',getAllUsers)
routes.post('/removesuggetion/:id',removeSuggetion)
routes.post('/reportpost',reportPost)
export default routes; 
